  const countryNameToCode = {
    "USA": "US",
    "UK": "GB",
    "S. Korea": "KR",
    "UAE": "AE",
    "Algeria": "DZ",
    "St. Barth": "BL",
    "St Vincent Grenadines": "VC",
    "British Virgin Islands": "VG",
    "Bolivia": "BO",
    "Bosnia" : "BA",
    "Brunei": "BN",
    "Cabo Verde": "CV",
    "CAR": "CF",
    "Caribbean Netherlands": "BQ",
    "Channel Islands": "JE",
    "Vanuatu": "VU",
    "Cura&ccedil;ao": "CW",
    "Czechia": "CZ",
    "Carribean Netherlands": "BQ",
    "DRC": "CD",
    "Antigua and Barbuda": "AG",
    "Dominican Republic": "DO",
    "Iran": "IR",
    "Equatorial Guinea": "GQ",
    "Burkina Faso": "BF",
    "Bosnia and Herzegovina": "BA",
    "Eswatini": "SZ",
    "Cook Islands": "CK",
    "Cayman Islands": "KY",
    "El Salvador": "SV",
    "Faeroe Islands": "FO",
    "Costa Rica": "CR",
    "French Guiana": "GF",
    "French Polynesia": "PF",
    "Falkland Islands": "FK",
    "Gibraltar": "GI",
    "Hong Kong": "HK",
    "Macao": "MO",
    "N. Korea": "KP",
    "New Zealand": "NZ",
    "Ivory Coast": "CI",
    "Isle of Man": "IM",
    "Libyan Arab Jamahiriya": "LY",
    "Montserrat": "MS",
    "Diamond Princess": "JP",
    "Myanmar": "MM",
    "New Caledonia": "NC",
    "Palestine": "PS",
    "Papua New Guinea": "PG",
    "Macedonia": "MK",
    "R&eacute;union": "RE",
    "Saint Martin": "MF",
    "Russia": "RU",
    "Saudi Arabia": "SA",
    "Sierra Leone": "SL",
    "South Africa": "ZA",
    "Micronesia": "FM",
    "Marshall Islands": "MH",
    "Laos": "LA",
    "MS Zaandam": "NL",
    "Moldova": "MD",
    "Sri Lanka": "LK",
    "South Sudan": "SS",
    "San Marino": "SM",
    "Saint Kitts and Nevis": "KN",
    "Saint Lucia": "LC",
    "Saint Helena": "SH",
    "Sao Tome and Principe": "ST",
    "St Martin": "MF",
    "Saint Pierre Miquelon": "PM",
    "Sint Maarten": "SX",
    "Syria": "SY",
    "Solomon Islands": "SB",
    "Taiwan": "TW",
    "Tanzania": "TZ",
    "Turks and Caicos": "TC",
    "Vietnam": "VN",
    "Trinidad and Tobago": "TT",
    "Wallis and Futuna": "WF",
    "Venezuela": "VE",
    "Vatican City": "VA",
    "Western Sahara": "ME",
  };

export { countryNameToCode };