export const developmentTools = [
    { tool: "Angular" },
    { tool: "APIs" },
    { tool: "Bitbucket" },
    { tool: "CSS" },
    { tool: "ChatGPT" },
    { tool: "Github" },
    { tool: "Gitlab" },
    { tool: "HTML" },
    { tool: "HUBL" },
    { tool: "Javascript" },
    { tool: "Liquid" },
    { tool: "Next.js" },
    { tool: "Node.js" },
    { tool: "NPM" },
    { tool: "React" },
    { tool: "React Native" },
    { tool: "Sass" },
    { tool: "Sourcetree" },
    { tool: "SVG" },
    { tool: "Vue" },    
    { tool: "Webpack" },
    { tool: "Wordpress" },
    { tool: "Webhooks" },
  ];

  export const productTools = [
    { tool: "Google Analytics" },
    { tool: "Google Optimize" },
    { tool: "Hotjar" },
    { tool: "Crazy Egg" },
    { tool: "Jira" },
    { tool: "Confluence" },
    { tool: "Slack" },
    { tool: "Trello" },
    { tool: "Asana" },
    { tool: "Notion" },
    { tool: "Miro" },
    { tool: "Agile" },
    { tool: "Scrum" },
    { tool: "Kanban" },
    { tool: "Lean" },
    { tool: "Design Thinking" },
  ];

  export const designTools = [
    { tool: "Adobe Photoshop" },
    { tool: "Adobe Illustrator" },
    { tool: "Adobe Indesign" },
    { tool: "Adobe XD" },
    { tool: "Adobe After Effects" },
    { tool: "Figma" },
    { tool: "Balsamiq" },
    { tool: "Midjourney" },
    { tool: "Uizard" },
    { tool: "Invision" },
    { tool: "Sketch" },
    { tool: "Framer" },
    { tool: "ProtoPie" },
    { tool: "Proto.io" },    
    { tool: "Zeplin" },
    { tool: "Atomic Design" },
    { tool: "Material Design" },
  ];